name: strihkod
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  get_cli: ^1.8.1
  get: 4.6.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_database: ^10.4.0
  freezed: ^2.4.7
  build_runner: ^2.4.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^3.0.7
  cloud_firestore: ^4.14.0
  json_theme: 6.3.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/themes/
